// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3QTOZvcKU4pa-mCMY6Y2dUIF9IP1A-tw',
    appId: '1:560541102593:web:167e5657b783dd9ee80600',
    messagingSenderId: '560541102593',
    projectId: 'growxproject',
    authDomain: 'growxproject.firebaseapp.com',
    storageBucket: 'growxproject.appspot.com',
    measurementId: 'G-YKD68DHYV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF6COdEPMmedvHOHLMUdtBrjHp2pK382g',
    appId: '1:560541102593:android:9cc794aadcc355b7e80600',
    messagingSenderId: '560541102593',
    projectId: 'growxproject',
    storageBucket: 'growxproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBe8fAsl3HmgZrx4-bmcZq12jZUZOBEdo',
    appId: '1:560541102593:ios:faf2cf3acd61c1a3e80600',
    messagingSenderId: '560541102593',
    projectId: 'growxproject',
    storageBucket: 'growxproject.appspot.com',
    iosClientId:
        '560541102593-82hi5t7tj6p0v092cl96qvku47evi0ak.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationGrowx',
  );
}
